# coordinator/Dockerfile
FROM python:3.9-slim
WORKDIR /app
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
ENV FLASK_APP=coordinator_app.py
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "coordinator_app:app"]