# prospective_intern/Dockerfile
FROM python:3.9-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENV FLASK_APP=prospective_intern_app.py
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "prospective_intern_app:app"]