from app import db

class Intern(db.Model):
    intern_id = db.Column(db.String(50), primary_key=True)
    full_name = db.Column(db.String(100), nullable=False)
    mobile = db.Column(db.String(20), nullable=False)
    nationality = db.Column(db.String(50), nullable=False)
    phone = db.Column(db.String(20), nullable=True)
    email = db.Column(db.String(50), nullable=False)
    alternate_email = db.Column(db.String(50), nullable=True)
    permanent_city = db.Column(db.String(50), nullable=False)
    date_of_birth = db.Column(db.Date, nullable=False)
    degree = db.Column(db.String(50), nullable=False)
    department = db.Column(db.String(50), nullable=False)
    college_name = db.Column(db.String(100), nullable=False)
    year_of_joining = db.Column(db.Integer, nullable=False)
    college_city = db.Column(db.String(50), nullable=False)
    college_state = db.Column(db.String(50), nullable=False)
    college_country = db.Column(db.String(50), nullable=False)
    gpa_type = db.Column(db.String(10), nullable=False)
    gpa_value = db.Column(db.Float, nullable=False)
    gender = db.Column(db.String(10), nullable=False)
    statement_of_purpose = db.Column(db.Text, nullable=False)
    can_complete_internship = db.Column(db.Boolean, nullable=False, default=False)
    faculty = db.Column(db.String(500), nullable=False)
    project_code = db.Column(db.String(10), nullable=False)
    time_stamp = db.Column(db.DateTime, nullable=False, default=db.func.current_timestamp())
    time_stamp_modified = db.Column(db.DateTime, nullable=False, default=db.func.current_timestamp(), onupdate=db.func.current_timestamp())